# 10장 예외 처리

잡히지 않은 예외가 발생하면 코루틴은 종료된다.

→ 코루틴 빌더는 부모도 종료시키며, 취소된 부모는 자식들 모두를 취소시킨다.

→ 코루틴이 예외를 받으면 자기 자신을 취소하고 예외를 부모로 전파한다.(launch)

→ 부모는 자기 자신과 자식들 모두를 취소하고 예외를 부모에게 전파한다.(runBlocking)

→ runBlocking은 부모가 없는 루트 코루틴이기 때문에 프로그램을 종료시킨다.(runBlocking은 예외를 다시 던진다)

```kotlin
fun main(): Unit = runBlocking {
	// launch 코루틴을 더하는 건 아무것도 바꾸지 못한다.
	launch {
		launch {
			delay(1000)
			throw Error("Some error")
		}
		
		launch {
			delay(2000)
			println("Will not be printed")
	  }
	  
	  launch {
		  delay(500) // 예외 발생보다 빠르다.
		  println("Will be printed")
		 }
	 }
	 
	 launch {
		 delay(2000)
		 println("Will not be printed")
	 }
 }
 // Will be printed
 // Exception in thread "main" java.lang.Error: Some error...
```

예외는 자식에서 부모로 전파되며, 부모가 취소되면 자식도 취소되기 때문에 쌍방으로 전파된다.

예외 전파가 정지되지 않으면 계통 구조상 모든 코루틴이 취소되게 된다.

![IMG_2F8B17A70540-1](https://github.com/woowacourse-study/2023-BookOverFlow/assets/50761690/d2b94254-9f3f-421a-8348-7af6dee586fd)


## 코루틴 종료 멈추기

코루틴이 종료되기 전에 예외를 잡는 건 도움이 되지만, 조금이라도 늦으면 이미 손쓸 수 없는 상황이 되어 버린다.

코루틴 간의 상호작용은 잡을 통해서 일어난다.

→ 코루틴 빌더 내부에서 새로운 코루틴 빌더를 try-catch 문을 통해 래핑하는 건 전혀 도움이 되지 못한다.

```kotlin
fun main(): Unit = runBlocking {
	// try-catch 구문으로 래핑하지 마세요. 무시됩니다.
	try {
		launch {
			delay(1000)
			throw Error("Some error")
		}
	} catch (e: Throwable) { // 여기선 아무 도움이 되지 않는다.
		println("Will not be printed")
	}
	launch {
		delay(2000)
		println("Will not be printed")
	}
}
// Exception in thread "main" java.lang.Error: Some error...
```

### SupervisorJob

자식에서 발생한 모든 예외를 무시할 수 있다. CoroutineContext로 다른 CoroutineContext들과 혼합해서 사용한다.

![IMG_97E6863FA978-1](https://github.com/woowacourse-study/2023-BookOverFlow/assets/50761690/30fe8dae-e610-4e4b-ae9d-abfd7e026629)

![IMG_4F1801B459B6-1](https://github.com/woowacourse-study/2023-BookOverFlow/assets/50761690/5ce70bb1-df8a-4aec-bb40-5f4099e2af5a)


SupervisorJob은 다수의 코루틴을 시작하는 스코프로 사용된다.

- 다수의 코루틴을 관리하면서도 각각의 독립성을 유지하는 데 사용된다.
- 부모 코루틴이 자식 코루틴들의 실패를 처리할 수 있다.

```kotlin
fun main(): Unit = runBlocking {
	val scope = CoroutineScope(SupervisorJob())
	scope.launch {
		delay(1000)
		throw Error("Some error")
	}
	
	scope.launch {
		delay(2000)
		println("Will be printed")
	}
	
	delay(3000)
}
// Exception...
// Will be printed
```

![IMG_3CA745599FE6-1](https://github.com/woowacourse-study/2023-BookOverFlow/assets/50761690/3f7b6ff5-f229-4b98-99ce-b696e05d6be3)


```kotlin
fun main(): Unit = runBlocking {
	// 이렇게 하지 마세요. 자식 코루틴 하나가 있고
	// 부모 코루틴이 없는 잡은 일반 잡과 동일하게 작동한다.
	launch(SupervisorJob()) {
		launch {
			delay(1000)
			throw Error("Some error")
		}
		
		launch {
			delay(2000)
			println("Will not be printed")
		}
	}
	
	delay(3000)
}
// Exception...
```

🚫 위의 코드처럼 하면 안되는 이유

- launch가 SupervisorJob을 인자로 받는데, 이럴 경우 SupervisorJob은 단 하나의 자식만 가지기 때문에 예외를 처리하는데 아무런 도움이 되지 않는다.
    
    → SupervisorJob을 Job 대신 사용하더라도 아무 도움이 되지 않는다.
    

하나의 코루틴이 취소되어도 다른 코루틴이 취소되지 않는다

→ 같은 잡을 다수의 코루틴에서 컨텍스트로 사용하는 것이 좀 더 나은 방법이다.

```kotlin
fun main(): Unit = runBlocking {
	val job = SupervisorJob()
	launch(job) {
		delay(1000)
		throw Error("Some error")
	}
	launch(job) {
		delay(2000)
		println("Will be printed")
	}
	job.join()
}
// (1초 후)
// Exception...
// (1초 후)
// Will be printed
```

### supervisorScope

코루틴 빌더를 supervisorScope로 래핑하는 것

다른 코루틴에서 발생한 예외를 무시하고 부모와의 연결을 유지한다.

```kotlin
fun main(): Unit = runBlocking {
	supervisorScope {
		launch {
			delay(1000)
			throw Error("Some error")
		}
		
		launch {
			delay(2000)
			println("Will be printed")
		}
	}
	delay(1000)
	println("Done")
}
// Exception...
// Will be printed
// (1초 후)
// Done
```

supervisorScope는 단지 중단 함수일 뿐이며, 중단 함수 본체를 래핑하는데 사용된다.

supervisoceScope 내부에 코루틴이 있다면 모든 코루틴은 SupervisorJob의 적용을 받게 된다.

<img width="738" alt="image" src="https://github.com/woowacourse-study/2023-BookOverFlow/assets/50761690/cbf71511-20dc-4c57-9b80-3649b17045aa">


supervisorScope를 사용하는 일반적인 방법은 서로 무관한 다수의 작업을 스코프 내에서 실행하는 것이다.

```kotlin
suspend fun notifyAnalytics(actions: List<UserAction>) = 
	supervisorScope {
		actions.forEach { action ->
			launch {
				notifyAnalytics(action_
			}
		}
	}
```

예외 전파를 멈추는 또 다른 방법은 `coroutineScope` 를 사용하는 것

- 코루틴 빌더와 달리 부모에 영향을 미치는 대신 try-catch를 이용해 잡을 수 있는 예외를 던진다.

❗**supervisorScope는 withContext(SupervisorJob())으로 대체될 수 없다.**

```kotlin
// 이렇게 하면 안된다!
suspend fun sendNotifications(
	notifications: List<Notification>
) = withContext(SupervisorJob()) {
	for (notification in notifications) {
		launch {
			client.send(notification)
		}
	}
}
/*
여기서 SupervisorJob은 withContext의 부모가 된다. 
자식 코루틴에서 예외가 발생하면 withContext 코루틴으로 전달이 되며, Job이 취소되고, 
자식 코루틴 또한 전부 취소되며, 마지막 예외가 던져진다.
-> SupervisorJob이 부모가 되어도 바뀌는 건 아무것도 없다.
*/
```

위 코드에서 `Job이 상속되지 않는 유일한 컨텍스트`이기 때문에 문제가 된다.

코루틴은 각각 자신만의 잡을 가지고 있고, 잡을 다른 코루틴에 전달하여 부모관계를 맺는다.

![IMG_04091877EB6E-1](https://github.com/woowacourse-study/2023-BookOverFlow/assets/50761690/f94c7bd2-f5b8-4677-880a-0a819a97c876)


### await

예외가 발생했을 때 async 코루틴 빌더는 launch 처럼 부모 코루틴을 종료하고 부모와 관련있는 다른 코루틴 빌더도 종료시킨다.

```kotlin
class MyException: Throwable()

suspend fun main() = supervisorScope {
	val str1 = async<String> {
		delay(1000)
		throw MyException()
	}
	
	val str2 = async {
		delay(2000)
		"Text2"
	}
	
	try {
		println(str1.await())
	} catch (e: MyException) {
		println(e)
	}
	
	println(str2.await())
}
// MyException
// Text2
```

코루틴이 예외로 종료되었기 때문에 반환할 값이 없지만, await가 MyException을 던지게 되어 MyException이 출력된다. 

supervisorScope가 사용되었기 때문에 또 다른 async는 중단되지 않고 끝까지 실행된다.

## CancellationException은 부모까지 전파되지 않는다.

예외가 `CancellationException의 서브클래스`라면 부모로 전파되지 않는다.

→ 현재 코루틴을 취소시킬 뿐이다.

→ CancellationException은 열린 클래스이기 때문에 다른 클래스나 객체로 확장될 수 있다.

```kotlin
object MyNonPropagatingException : CancellationException()

suspend fun main(): Unit = coroutineScope {
	launch { // 1
		launch { // 2
			delay(2000)
			println("Will not be printed")
		}
		throw MyNonPropagatingException // 3
	}
	launch { // 4
		delay(2000)
		println("Will be printed")
	}
}
// (2초 후)
// Will be printed
```

## 코루틴 예외 핸들러

**CoroutineExceptionHandler 컨텍스트 사용**

- 예외 전파를 중단시키지는 않지만 예외가 발생했을 때 해야 할 것들을 정의하는데 사용
- 에러가 발생했을 때 실행되는 람다식

```kotlin
fun main(): Unit = runBlocking {
	val handler = 
		CoroutineExceptionHandler { ctx, exception ->
			println("Caught $exception")
		}
	val scope = CoroutineScope(SupervisorJob() + handler)
	scope.launch {
		delay(1000)
		throw Error("Some error")
	}
	
	scope.launch {
		delay(2000)
		throw Error("Will be printed")
	}
	
	delay(3000)
}
```

다양한 플랫폼에서 예외를 처리하는 기본적으로 방법을 추가할 때 CoroutineExceptionHandler 컨텍스트를 활용할 수 있다.
❗코루틴에서 공통 예외처리기가 필요할 때 CoroutineExceptionHandler를 사용하자
