# 10장 예외처리

> 예외가 발생했을 시 코루틴 자기 자신을 취소하고 예외를 부모로 전파한다.
> 부모는 자기 자신과 자식들 모두를 취소하고 예외를 부모에게 전파한다.
> runBlocking은 부모가 없는 루트 코루틴이기 때문에 프로그램을 종료한다.

```kotlin 
fun main(): Unit = runBlocking {
	launch {
		launch {
			delay(1000)
			throw Error("Some error")
		}

		launch {
			delay(2000)
			println("Will not be printed")
		}

		launch {
			delay(500) // 예외 발생보다 빠르다.
			println("Will be printed")
		}
	}

	launch {
		delay(2000)
		println("Will not be printed")
	}
}

// Will be printed
// Exception in thread "main" ....
```

> launch 코루틴을 더하는 건 아무것도 바꾸지 못한다. 예외는 자식에서 부모로 전파되며, 부모가 취소되면 자식도 취소되기 때문에 쌍방으로 전파된다.
> 예외 전파가 정지되지 않으면 계통 구조상 모든 코루틴이 취소되게 한다.

![IMG_2F8B17A70540-1](https://github.com/woowacourse-study/2023-BookOverFlow/assets/50761690/d2b94254-9f3f-421a-8348-7af6dee586fd)

## 코루틴 종료 멈추기
> 코루틴 간의 상호작용은 잡을 통해서 일어나기 때문에, 코루틴 빌더 내부에서 새로운 코루틴 빌더를 try-catch문을 통해 래핑하는 것은 의미 없다.

```kotlin
fun main(): Unit = runBlocking {
	// try-catch 구문으로 래핑하지 마세요. 무시됩니다.
	try {
		launch {
			delay(1000)
			throw Error("Some error")
		}
	} catch (e: Throwable) { // 여기선 아무 도움이 되지 않는다.
		println("Will not be printed")
	}
	launch {
		delay(2000)
		println("Will not be printed")
	}
}
// Exception in thread "main" java.lang.Error: Some error...
```

### SupervisorJob
> SupervisorJob을 사용하면 자식에서 발생한 모든 예외를 무시할 수 있다.

![](https://private-user-images.githubusercontent.com/50761690/311423570-30fe8dae-e610-4e4b-ae9d-abfd7e026629.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNTIwNzksIm5iZiI6MTcxMDA1MTc3OSwicGF0aCI6Ii81MDc2MTY5MC8zMTE0MjM1NzAtMzBmZThkYWUtZTYxMC00ZTRiLWFlOWQtYWJmZDdlMDI2NjI5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwNjIyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDczM2YwMmM5MzM0ZDA4MTBhMDI5OWRkNGZlMmRlOWU3Zjc0YzAzZjc4NGQ4YjNhN2IyZDVmMzMwNDk1ZDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rtk5meQWcoBBO4UL7lzp3_RWAbORp_u-Vf6Q6z80veU)

![](https://private-user-images.githubusercontent.com/50761690/311423581-5ce70bb1-df8a-4aec-bb40-5f4099e2af5a.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNTIwNzksIm5iZiI6MTcxMDA1MTc3OSwicGF0aCI6Ii81MDc2MTY5MC8zMTE0MjM1ODEtNWNlNzBiYjEtZGY4YS00YWVjLWJiNDAtNWY0MDk5ZTJhZjVhLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwNjIyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2QwNTZhZGQxZWUzNmY2ZmZiMzRjNjU3MGQwMTIxYTI2NmE5YzI5NTU0ZjkzYmFjZDM1NzFkZWRkOWRkYTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dYhEl-VHwetET153KwpAeQ6pq2wZSolbfbb1u10388c)

> 흔한 실수 중 하나는 SupervisorJob을 다음 코드처럼 부모 코루틴의 인자로 사용하는 것이다. 1에서 정의된 launch가 SupervisorJob을 인자로 받는데, 이럴 경우 SupervisorJob은 단 하나의 자식만 가지기 때문에 예외를 처리하는 데 아무런 도움이 되지 않는다. 따라서 SupervisorJob을 Job 대신 사용하더라도 아무 도움이 되지 않는다.
> (두 경우 모두 runBlocking의 잡을 사용하지 않기 때문에 예외는 runBlocking으로 전파되지 않는다.)

```kotlin
fun main(): Unit = runBlocking {
	// 이렇게 하지 마세요. 자식 코루틴 하나가 있고
	// 부모 코루틴이 없는 잡은 일반 잡과 동일하게 작동한다.
	launch(SupervisorJob()) {
		launch {
			delay(1000)
			throw Error("Some error")
		}
		
		launch {
			delay(2000)
			println("Will not be printed")
		}
	}
	
	delay(3000)
}
// Exception...
```

> 하나의 코루틴이 취소되어도 다른 코루틴이 취소되지 안흔ㄴ다는 점에서, 같은 잡을 다수의 코루틴에서 컨텍스트로 사용하는 것이 좀더 나은 방법이다.

```kotlin
fun main(): Unit = runBlocking {
	val job = SupervisorJob()
	launch(job) {
		delay(1000)
		throw Error("Some error")
	}
	launch(job) {
		delay(2000)
		println("Will be printed")
	}
	job.join()
}
// (1초 후)
// Exception...
// (1초 후)
// Will be printed
```

### supervisorScope
> 에외 전파를 막는 또 다른 방법은 코루틴 빌더를 supervisorScpoe로 래핑하는 것이다.
> 다른 코루틴에서 발생한 예외를 무시하고 부모와의 연결을 유지한다는 점에서 아주 편리하다.

```kotlin
fun main(): Unit = runBlocking {
	supervisorScope {
		launch {
			delay(1000)
			throw Error("Some error")
		}
		
		launch {
			delay(2000)
			println("Will be printed")
		}
	}
	delay(1000)
	println("Done")
}
// Exception...
// Will be printed
// (1초 후)
// Done
```

> 이 스코프는 단지 중단 함수일 뿐이며, 중단 함수 본체를 래핑하는 데 사용된다.
> 이 스코프를 사용하는 일반적인 방법은 서로 무관한 다수의 작업을 스코프 내에서 실행하는 것이다.

```kotlin
suspend fun notifyAnalytics(actions: List<UserAction>) = supervisorScope {
	actions.forEach { action ->
		launch {
			notifyAnalytics(action)
		}
	}
}
```

> 예외 전파를 멈추는 또 다른 방법은 coroutineScope를 사용하는 것이다.
> 이 함수는 코루틴 빌더와 달리 부모에 영향을 미치는 대신 try-catch를 이용해 잡을 수 있는 예외를 던진다.

## await
> 예외가 발생했을 때 async 코루틴 빌더는 launch처럼 부모 코루틴을 종료하고 부모와 관련있는 다른 코루틴 빌더도 종료시킨다.
> SupervisorJob이나 superviosrScope를 사용하면 이런 과정이 일어나지 않는데, await을 호출하면 어떻게 될까?

```kotlin
class MyException : Throwable()

suspend fun main() = supervisorScope {
	val str1 = async<String> {
		delay(1000)
		throw MyException()
	}

	val str2 = async {
		delay(2000)
		"Text2"
	}

	try {
		println(st1.await())
	} catch (e: MyException) {
		println(e)
	}

	println(str2.await())
}
// MyException
// Text2
```

> 코루틴이 예외로 종료되었기 때문에 반환할 값이 없지만, await이 MyException을 던지게 되어 MyException이 출력된다.
> supervisorScope가 사용되었기 때문에 또 다른 async는 중단되지 않고 끝까지 실행된다.

## CancellationException은 부모까지 전파되지 않는다.
> 에외가 CancellationException의 서브클래스라면 부모로 전파되지 않는다.
> 현재 코루틴을 취소시킬 뿐이다.
> CancellationException은 열린 클래스이기 때문에 다른 클래스나 객체로 확장될 수 있다.

```kotlin
object MyNonPropagatingException: CancellationException()

suspend fun main(): Unit = coroutineScope {
	launch { // 1
		launch { // 2
			delay(2000)
			println("Will not be printed")
		}
		throw MyNonProgatingException // 3
	}
	launch { // 4
		delay(2000)
		println("Will be printed")
	}
}
// (2초 후)
// Will be printed
```

> 앞 코드에서 두 개의 코루틴이 1과 4의 빌더로 시작된다.
> 3에서 CancellationException의 서브타입인 MyNonProgatingException 예외를 던진다.
> 예외는 1에서 시작된 launch에서 잡히게 된다.
> 1에서 시작된 코루틴은 자기 자신을 취소하고 2에서 정의된 빌더로 만들어진 자식 코루틴 또한 취소한다.
> 4에서  두 번째 lauch는 영향을 받지 않고 2초 후에 Will be printed를 출력한다.

## 코루틴 예외 핸들러
> 예외를 다룰 때 예외를 처리하는 기본 행동을 정의하는 것이 유용할 때가 있다.
> 이런 경우 CoroutineExceptionHandler 컨텍스트를 사용하면 편리하다.
> 예외 전파를 중단시키지는 않지만 예외가 발생했을 때 해야 할 것들(기본적으로 예외 스택 트레이스를 출력한다.)을 정의하는 데 사용할 수 있다.

```kotlin
fun main(): Unit = runBlocking {
	val handler = CoroutineExceptionHandler { ctx, exception ->
		println("Caught $exception")
	}
	val scope = CoroutineScope(SupervisorJob() + handler)
	scope.launch {
		delay(1000)
		throw Error("Some error")
	}

	scope.launch {
		delay(2000)
		println("Will be printed")
	}

	delay(3000)
}
// Caught java.lang.Error: Some error
// Will be printed
```

> 안드로이드에서는 에러 메시지를 표현함으로 써 어떤 문제가 발생했는지 알리는 역할을 할 수도 있다.

## 요약
> 예외 처리는 kotlinx.coroutines 라이브러리의 중요한 기능이다.
> 지금은 기본 빌더에서 예외가 자식에서 부모로 전파되는 것을 이해하고 어떻게 멈추는 지만 이해하면 된다.
