# 예외 처리

- 예외 처리는 코루틴의 작동 원리 중 아주 중요한 기능이다.
- 일단 프로그램처럼 코루틴도 잡히지 않은 예외가 발생하면 종료된다.
- **코루틴 빌더는 부모도 종료시키며, 취소된 부모는 자식들 모두를 취소시킨다.**

<br>

```kotlin
suspend fun main(): Unit = runBlocking {
    launch {
        launch {
            delay(1000)
            throw Error("Krrong")
        }

        launch {
            delay(2000)
            println("출력되지 않음")
        }

        launch {
            delay(500)
            println("출력됨")
        }

        launch {
            delay(2000)
            println("출력되지 않음")
        }
    }
}
```

- 실행 결과
    
    ```kotlin
    출력됨
    Exception in thread "main" java.lang.Error: Krrong
    ```
    
- 코루틴이 예외를 받았을 때 자기 자신을 취소하고 예외를 부모로 전파한다.(launch)
- 부모는 자기 자신과 자식들 모두를 취소하고 예외를 부모에게 전파한다.(runBlocking)
- runBlocking은 부모가 없는 루트 코루틴이기 때문에 프로그램을 종료시킨다. (이 때 runBlocking도 예외를 다시 던진다.)

<br>

<img src="https://github.com/woowacourse-study/2023-BookOverFlow/assets/84285337/c9f7920f-bdc1-42cf-8603-2d4345580d37">

- **예외는 자식에서 부모로 전파되며, 부모가 취소되면 자식도 취소되기 때문에 쌍방으로 전파된다.**
- 예외 전파가 정지되지 않으면 계통 구조상 모든 코루틴이 취소된다.

<br><br>

## 코루틴 종료 멈추기

- 코루틴 간의 상호작용은 잡을 통해서 일어나기 때문에, 코루틴 빌더 내부에서 새로운 코루틴 빌더를 try-catch문으로 래핑하는 것은 전혀 도움되지 않는다.

<br>

```kotlin
suspend fun main(): Unit = runBlocking {
    try {
        launch {
            delay(1000)
            throw Error("Krrong")
        }
    } catch (e: Error) {
        println("출력되지 않음")
    }
    launch {
        delay(2000)
        println("출력되지 않음")
    }
}
```

- 실행 결과
    
    ```kotlin
    Exception in thread "main" java.lang.Error: Krrong
    ```
    
<br><br>

## SupervisorJob

- 코루틴 종료를 멈추는 가장 중요한 방법은 SupervisorJob을 사용하는 것이다.
- **SupervisorJob을 사용하면 자식에서 발생한 모든 예외를 무시할 수 있다.**

<br>

<img src="https://github.com/woowacourse-study/2023-BookOverFlow/assets/84285337/687275d2-ffec-4d9d-9c65-1f89bb2b7e70">

<img src="https://github.com/woowacourse-study/2023-BookOverFlow/assets/84285337/c9894a69-bb23-414c-9e0b-825c367d78a1">

- 일반적으로 SupervisorJob은 다수의 코루틴을 시작하는 스코프로 사용된다.

<br>

```kotlin
suspend fun main(): Unit = runBlocking {
    val scope = CoroutineScope(SupervisorJob())
    scope.launch {
        delay(1000)
        throw Error("Krrong")
    }

    scope.launch {
        delay(2000)
        println("출력됨")
    }

    delay(3000)
}
```

- 실행 결과
    
    ```kotlin
    Exception in thread "DefaultDispatcher-worker-1" java.lang.Error: Krrong
    출력됨
    ```

<br>    

```kotlin
suspend fun main(): Unit = runBlocking {
    launch(SupervisorJob()) { // 1
        launch {
            delay(1000)
            throw Error("Krrong")
        }
        launch {
            delay(2000)
            println("출력안됨")
        }
    }

    delay(3000)
}
```

- 실행 결과
    
    ```kotlin
    Exception in thread "DefaultDispatcher-worker-1" java.lang.Error: Krrong
    ```
    

- 1에서 정의된 launch가 SupervisorJob을 부모 코루틴의 인자로 사용하더라도 SupervisorJob은 단 하나의 자식만 가지기 때문에 예외를 처리하는데 아무런 도움도 되지 않는다. (1번 launch가 자식이 된다.)
- SupervisorJob을 Job대신 사용하더라도 마찬가지다.
- 두 경우 모두 runBlocking의 Job을 사용하지 않기 때문에 예외는 runBlocking으로 전파되지 않는다.
- 하나의 코루틴이 취소되어도 다른 코루틴이 취소되지 않는다는 점에서, 같은 Job을 다수의 코루틴에서 컨텍스트로 사용하는 것이 좀 더 나은 방법이다.

<br><br>

## supervisorScope

- 예외 전파를 막는 다른 방법은 코루틴 빌더를 supervisorScope로 래핑하는 것이다.
- 다른 코루틴에서 발생한 예외를 무시하고 부모와의 연결을 유지한다는 점에서 아주 편리하다.

<br>

```kotlin
suspend fun main(): Unit = runBlocking {
    supervisorScope {
        launch {
            delay(1000)
            throw Error("Krrong")
        }
        launch {
            delay(2000)
            println("출력됨")
        }
    }

    delay(1000)
    println("종료")
}
```

- 실행 결과
    
    ```kotlin
    Exception in thread "main" java.lang.Error: Krrong
    출력됨
    (1초 후)
    종료
    ```
    

- supervisorScope는 단지 중단 함수일 뿐이며, 중단 함수 본체를 래핑하는 데 사용된다.
- supervisorScope를 사용하는 일반적인 방법은 서로 무관한 다수의 작업을 스코프 내에서 실행하는 것이다.

<br>

- 예외 전파를 멈추는 또 다른 방법은 coroutineScope를 사용하는 것이다.
- 이 함수는 코루틴 빌더와 달리 부모에 영향을 미치는 대신 try-catch를 이용해 잡을 수 있는 예외를 던진다.

<br>

> supervisorScope는 withContext(SupervisorJob())으로 대체될 수 없다!!
> 

```kotlin
suspend fun sendNotifications(
    notifications: List<Notification>
) = withContext(SupervisorJob()) {
    for (notification in notifications) {
        launch {
            client.send(notification)
        }
    }
}
```

- 위 코드는 Job이 상속되지 않는 유일한 컨텍스트이기 때문에 문제가 된다.
- 코루틴은 각각 자신만의 Job을 가지고 있고, Job을 다른 코루틴에 전달하여 부모 관계를 맺는다.
- 여기서는 SupervisorJob이 withContext의 부모가 된다.
- 자식 코루틴에서 발생한 예외는 withContext로 전달이 되고, Job이 취소되고 자식 코루틴 또한 모두 취소되고 마지막으로 예외가 던져진다.

<img src="https://github.com/woowacourse-study/2023-BookOverFlow/assets/84285337/a9155a03-2199-4387-827d-e8acf9af3b31">

<br><br>

## await

- 예외가 발생했을 때 async 코루틴 빌더는 launch 처럼 부모 코루틴을 종료하고 부모와 관련있는 다른 코루틴 빌더도 종료시킨다.
- SupervisorJob이나 supervisorScope를 사용하면 이런 과정이 일어나지 않는데, await을 호출하면 어떻게 될까?

<br>

```kotlin
class KrrongException: Throwable()

suspend fun main(): Unit = supervisorScope {
    val str1 = async<String> {
        delay(1000)
        throw KrrongException()
    }

    val str2 = async<String> {
        delay(2000)
        "Text"
    }

    try {
        println(str1.await())
    } catch (e: KrrongException) {
        println(e)
    }

    println(str2.await())
}
```

- 실행 결과
    
    ```kotlin
    KrrongException
    Text
    ```
    
<br>

- 코루틴이 예외로 종료되었기 때문에 반환할 값이 없지만, await이 KrrongException을 던지게 되어 KrrongException을 출력한다. supervisorScope를 사용하였기 때문에 다른 async는 중단되지 않고 끝까지 실행된다.

<br>

<aside>
💡 위 코드에서 supervisorScope를 runBlocking으로 바꾸면 어떻게 될까?

</aside>

- KrrongException만 출력한 뒤에 프로그램이 예외로 종료된다.

<br><br>

## CancellationException은 부모까지 전파되지 않는다

- 예외가 CancellationException의 서브 클래스라면 부모로 전파되지 않는다.
- 현재 코루틴을 취소시킨다.
- CancellationException은 오픈 클래스이기 때문에 다른 클래스나 객체로 확장될 수 있다.

<br>

```kotlin
class KrrongException: CancellationException()

suspend fun main(): Unit = coroutineScope {
    launch {     // 1
        launch { // 2
            delay(2000)
            println("출력되지 않음")
        }
        throw KrrongException()  // 3
    }

    launch {     // 4
        delay(2000)
        println("출력됨")
    }
}
```

- 실행 결과
    
    ```kotlin
    (1초 후)
    출력됨
    ```
    

- 두 개의 코루틴이 1, 4의 빌더로 시작된다.
- 3에서 CancellationException의 서브 클래스 예외를 던지고 이 예외는 1에서 시작된 launch에서 잡힌다.
- 1에서 시작된 코루틴은 자기 자신을 취소하고 2에서 정의된 빌더로 만들어진 자식 코루틴 또한 취소시킨다.
- 4에서 시작된 두 번째 launch는 영향을 받지 않고 2초 후에 출력됨을 출력한다.

<br><br>

## 코루틴 예외 핸들러

- 예외를 다룰 때 예외를 처리하는 기본 행동을 정의하는 것이 유용할 때가 있다.
- 이런 경우 CoroutineExceptionHandler 컨텍스트를 사용하면 편리하다.
- 예외 전파를 중단시키지 않지만 예외가 발생했을 때 해야 할 것들을 정의하는데 사용할 수 있다.

<br>

```kotlin
suspend fun main(): Unit = runBlocking {
    val handler = CoroutineExceptionHandler { ctx, exception ->
        println("Caught $exception")
    }

    val scope = CoroutineScope(SupervisorJob() + handler)

    scope.launch {
        delay(1000)
        throw Error("Krrong")
    }

    scope.launch {
        delay(2000)
        println("출력됨")
    }

    delay(3000)
}
```

- 실행 결과
    
    ```kotlin
    (1초 후)
    Caught java.lang.Error: Krrong
    (1초 후)
    출력됨
    ```
    

<br><br>

## 요약

- 자식 코루틴에서 예외가 발생하면 부모로 전파되어 부모 또한 예외로 취소되며 취소된 부모는 모든 자식 코루틴을 취소한다.
- 코루틴 종료를 멈추기 위해 SupervisorJob, supervisorScope 를 사용할 수 있다.
- SupervisorJob
    - 자식에서 발생한 예외를 무시할 수 있다.
- supervisorScope
    - 코루틴 빌더를 supervisorScope로 래핑하면 다른 코루틴에서 발생한 예외는 무시하고 부모 코루틴과의 관계는 유지한다.
    - 일반적으로 서로 무관한 다수의 작업을 스코프 내에서 실행할 때 사용한다.
    - supervisorScope는 withContext(SupervisorJob())으로 대체될 수 없다!!
- coroutineScope
    - 코루틴 빌더와 달리 부모에 영향을 미치는 대신 try-catch를 이용해 잡을 수 있는 예외를 던진다.
- 예외가 CancellationException의 서브 클래스라면 부모로 전파되지 않는다.
- CoroutineExceptionHandler 컨텍스트를 정의하여 코루틴에서 예외가 발생했을 떄 하는 행동을 정의할 수 있다. (예외 전파를 막지는 않는다.)