# 9장 취소

Created: March 9, 2024 4:34 PM

# 기본적인 취소

Job 인터페이스는 취소할 수 있는 cancel 메서드를 가진다.

### cancel 메서드 호출 시 효과

- 호출한 코루틴은 첫 번째 중단점에서 잡을 끝낸다.
- 잡이 자식을 가지고 있다면, 자식들도 취소된다. 하지만 부모는 영향 받지 않는다.
- 취소된 잡은 `Cancelling` → `Cancelled` 상태로 바뀌며, 새로운 코루틴의 부모로 사용될 수 없다.

cancel 함수에 각기 다른 예외를 인자로 넣는 방법을 사용하면 취소된 원인을 명확하게 전달할 수 있다. 이 때, 코루틴을 취소하기 위해 사용되는 예외는 `CancellationException`이어야 하기 때문에 인자로 사용되는 예외는 반드시 `CancellationException`의 서브타입이어야 한다.

cancel이 호출된 후 다음 작업을 진행하기 전에, 취소 과정이 완료되는 것을 기다리기 위해 join을 사용하는 것이 일반적이다. join을 호출하지 않으면 경쟁 상태(race condition)이 될 수 있다.

```kotlin
suspend fun main() = coroutineScope {
	val job = launch {
		repeat(1_000) { i ->
			delay(100)
			Thread.sleep(100) // 오래 걸리는 연산이라 가정
			println("Printing $i")
		}
	}
	
	delay(1000)
	job.cancel()
	// job.join()을 추가하면 취소를 마칠 때까지 중단 -> 경쟁 상태 발생 X
	println("Cancelled successfully")
}
// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Cancelled successfully
// Printing 4
```

kotlinx.coroutine 라이브러리는 call과 join을 함께 호출할 수 있도록 `cancelAndJoin`이라는 확장 함수를 제공한다.

```kotlin
public suspend fun Job.cancelAndJoin
```

이 방법으로 Job() 팩토리 함수로 생성된 잡을 취소할 수 있다. 잡의 자식 코루틴들을 한번에 취소할 때 자주 사용한다.

ex) 수행되는 작업 그룹 전체를 취소시켜야할 때, 사용자가 뷰를 나갔을 때 뷰에서 시작된 모든 코루틴을 취소하는 경우

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		repeat(1_000) { i ->
			delay(200)
			println("Printing $i")
		}
	}
	
	delay(1100)
	job.cancelAndJoin()
	println("Cancelled successfully")
}
// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Printing 4
// Cancelled successfully
```

# 취소는 어떻게 작동하는가?

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		try {
			repeat(1_000) { i ->
				delay(200)
				println("Printing $i")
			}
		} catch (e: CancellationException) {
			println(e)
			throw e // 예외를 잡을 수 있지만 다시 던져주는 것이 좋다.
		}
	}
	delay(1100)
	job.cancelAndJoin()
	println("Cancelled successfully")
	delay(1000)
}
// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Printing 4
// kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@51bebf23
// Will always be printed
// Cancelled successfully
```

잡이 취소되면 `Cancelling` 상태로 바뀌는데, 상태가 바뀐 후 첫 번째 중단점에서 `CancellationException` 예외를 던진다.

취소된 코루틴이 단지 멈추는 것이 아닌, 내부적으로 예외를 사용하여 취소되는 것이기 때문에 `finally` 블록 안에서 모든 것을 정리할 수 있다.

ex) 파일, 데이터베이스 연결 닫기

# 취소 중 코루틴을 한 번 더 호출하기

코루틴은 정리 과정 중에 중단을 허용하지 않는다. Job이 이미 `Cancelling` 상태가 되면 중단되거나 다른 코루틴을 시작하는 것은 불가능하다.

다른 코루틴을 시작하려고 하면 무시되고, 중단하려고 하면 `CancellationException`을 던진다.

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		try {
			delay(2000)
			println("Job is done")
		} finally {
			println("Finally")
			launch { // 무시
				println("Will not be printed")
			}
			delay(1000) // 예외 발생 (delay도 중단이니까)
			// 그래서 이 delay에서 나오는 CancellationException도 try-catch로 잡을 수도 있음
			println("Will not be printed")
		}
	}
	delay(1000)
	job.cancelAndJoin()
	println("Cancel done")	
}
// (1초 후)
// Finally
// Cancel done
```

코루틴이 이미 취소되었을 때 중단 함수를 반드시 호출해야하는 경우도 있는데, 함수 콜을 `withContext(NonCancellable)`로 포장하는 방법이 많이 사용된다. **취소될 수 없는 Job**인 `NonCancellable` 객체를 사용하여 컨텍스트를 바꾼다.

블록 내부에서 잡을 액티브 상태로 유지해서 중단 함수를 원하는 만큼 호출할 수 있다.

ex) 데이터베이스의 변경사항을 롤백하는 경우

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		try {
			delay(200)
			println("Coroutine finished")
		} finally {
			println("Finally")
			withContext(NonCancellable) {
				delay(1000L)
				println("Cleanup done")
			}
		}
	}
	delay(100)
	job.cancelAndJoin()
	// 여기서 NonCancellable cancelAndJoin하면 에러남, NonCancellable은 취소될 수 없으니까
	println("Done")
}
// Finally
// Cleanup done
// Done
```

# invokeOnCompletion

자원 해제에 자주 사용되는 또 다른 방법 → Job의 `invokeOnCompletion` 메서드 호출하기

⇒ 잡이 `Completed`나 `Cancelled`와 같은 마지막 상태에 도달했을 때 호출될 핸들러 지정하는 역할

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = launch {
		delay(1000)
	}
	job.invokeOnCompletion { exception: Throwable? ->
		println("Finished")
	}
	delay(400)
	job.cancelAndJoin()
}
// Finished
```

### 핸들러에 올 수 있는 exception 종류

- 잡이 예외 없이 끝나면 null
- 코루틴이 취소되었으면 `CancellationException`
- 코루틴을 종료시킨 예외

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = launch {
		delay(Random.nextLong(2400))
		println("Finished")
	}
	delay(800)
	job.invokeOnCompletion { exception: Throwable? ->
		println("Will always be printed")
		println("The exception was: $exception")
	}
	delay(800)
	job.cancelAndJoin()
}
```

### 의문점

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = launch {
//        delay(100)
//        delay(800)
//        delay(1200)
        delay(1600)
//        delay(2400)
        println("Finished")
    }
    delay(800)
    job.invokeOnCompletion { exception: Throwable? ->
        println("Will always be printed")
        println("The exception was: $exception")
        println("===")
    }
    delay(800)
    job.cancelAndJoin()
    // delay(100) -- (1)
    println("end")
}

// Finished
// Will always be printed
// end
// 왜 exception이랑 end 출력이 안될까?
```

(1)을 추가하면 exception과 end가 출력이 되지만, 추가하지 않으면 출력이 안된다.

(추측) println가 속도가 빠른 작업이 아니라서, println 하기 전에 main이 끝나서 출력이 되다 만다!

잡이 `invokeOnCompletion`이 호출되기 전에 완료되었으면 핸들러는 즉시 호출된다. `onCancelling`과 `invokeImmediately` 파라미터를 사용해서 핸들러 동작 방식을 변경할 수 있다.

- `onCancelling` : true면 ‘Cancelling’ 상태에서 호출 (default value = false)
- `invokeImmediately` : 이미 해당 상태일 때 핸들러가 지정되었다면 핸들러를 즉시 호출할지 여부 결정 (default value = true)

`invokeOnCompletion`은 취소 중에 동기적으로 호출되며, 어떤 스레드에서 실행할지 결정할 수 없다.

# 중단될 수 없는 걸 중단하기

취소는 중단점에서 일어나기 때문에 중단점이 없으면 취소할 수 없다.

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		repeat(1_000)
	}
}
```

ex) 작업 중에 복잡한 연산이나 파일을 읽는 등의 작업이 있을 때, 중단점이 없으면 취소가 불가하다.

아래 방법으로 해결할 수 있다.

## yield()

`yield()`를 주기적으로 호출하는 방법이다. yield는 코루틴을 중단하고 즉시 재실행한다. (중단함수)

중단점이 생겼기 때문에 취소나 디스패처를 사용하여 스레드를 바꾸는 일을 포함하여, 중단(또는 재실행) 중에 필요한 모든 작업을 할 수 있는 기회가 생긴다.

중단 불가능하면서 CPU 집약적 or 시간 집약적인 연산들이 중단 함수에 있다면, 연산 사이에 yield를 사용해주는 것이 좋다.

## Job 상태 추적

코루틴 빌더 내부에서 this(리시버)는 빌더 스코프를 참조한다. 따라서, CoroutineScope는 coroutineContext 프로퍼티를 사용해서 참조할 수 있는 컨텍스트를 가지고 있고, coroutineContext[Job] or coroutineContext.job에 접근하여 현재 상태를 알 수 있다.

Job의 역할 → 코루틴 상태 확인용 → 라이브러리에서 이걸 확인하는 간단한 함수를 제공한다.

```kotlin
public val CoroutineScope.isActive: Boolean
	get() = coroutineContext[Job]?.isActive ?: true
```

이 프로퍼티를 사용해서 `isActive`를 검사한다!

```kotlin
suspend fun main(): Unit = coroutineScope {
  val job = Job()
	launch(job) {
		do {
			Thread.sleep(200)
			println("Printing")
		while (isActive)
	}
	delay(1100)
	job.cancelAndJoin()
	println("Cancelled successfully")
}
// Printing
// Printing
// Printing
// Printing
// Printing
// Printing
// Cancelled successfully
```

또는 `ensureActive()` 함수를 사용할 수 있다. 이 함수는 Job이 Active 상태가 아닐 때 `CancellationException`을 던진다.

```kotlin
suspend fun main(): Unit = coroutineScope {
  val job = Job()
	launch(job) {
		repeat(1000) { num ->
			Thread.sleep(200)
			ensureActive()
			println("Printing $num")
		}
	}
	delay(1100)
	job.cancelAndJoin()
	println("Cancelled successfully")
}
// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Printing 4
// Cancelled successfully
```

## yield() vs ensureActive()

| yield() | ensureActive() |
| --- | --- |
| 전형적인 최상위 중단 함수
스코프 필요 X → 일반적인 중단 함수에서도 사용 가능 | CoroutineScope(or CoroutineContext or Job)에서 호출 |
| 중단-재개를 하는 역할이기 대문에 스레드 풀을 가진 디스패처 사용 시 스레드가 바뀌는 문제 발생 가능 | 좀더 가벼워서 선호됨 |
| CPU 사용량이 크거나 스레드를 블로킹하는 중단 함수에서 자주 사용 |  |

# suspendCancellableCoroutine

`suspendCancellableCoroutine` 함수는 `suspendCoroutine`과 비슷하지만, 컨티뉴에이션 객체를 몇 가지 메서드가 추가된 `CancellableContinuation<T>` 로 래핑한다.

```kotlin
suspend fun someTask() = suspendCancellabeCoroutine { cont ->
	cont.invokeOnCancellation { // 중요!!!
		// 정리 작업 수행
	}
	// 나머지 구현 부분
}
```

`invokeOnCancellation` 메서드는 라이브러리의 실행을 취소하거나 자원을 해제할 때 주로 사용한다.

Retrofit Call을 중단 함수로 래핑하면서, continuation.invokeOnCancellation 내부에서 Call을 cancel()하는 것처럼 실행 취소하는 로직을 사용할 수 있다.

그리고 Retrofit도 중단 함수를 지원한다.

`CancellableContinuation<T>`도 isActive, isCompleted, isCancelled 프로퍼티를 통해 잡의 상태를 확인할 수 있으며, 컨티뉴에이션을 취소할 때 취소가 되는 원인을 추가적으로 제공할 수 있다.

# 요약

취소를 적절하게 사용하면 자원 낭비와 메모리 누수를 줄일 수 있다.